### ISSUE TITLE
tabellenlinien dicker machen

### ISSUE THREAD

**Issue by Schoergi1** [ValentinHoerzi/Diplomarbeit-ERM#10]

**Comment by Schoergi1** [comment]
tabellenlinien sind jetzt 1pt dick

Ich drucke diese seite einmal aus und sieh es mir da dann an ob die Linien da sind

**Comment by ValentinHoerzi** [comment]
> tabellenlinien sind jetzt 1pt dick
> 
> Ich drucke diese seite einmal aus und sieh es mir da dann an ob die Linien da sind

Und wie schauts aus?
