### ISSUE TITLE
geschlossene Produktpalette neues Bild machen

### ISSUE THREAD

**Issue by Schoergi1** [ValentinHoerzi/Diplomarbeit-ERM#16]

**Comment by Schoergi1** [comment]
Und dann in Punkt 8.5 einfügen

**Comment by ValentinHoerzi** [comment]
kemma ds scho closen?

**Comment by Schoergi1** [comment]
I kan mi nu ima ned anmelden

**Comment by ValentinHoerzi** [comment]
![image](https://user-images.githubusercontent.com/38781974/109859642-816ae080-7c5d-11eb-87d0-f076a5a22909.png)
passt des?

**Comment by Schoergi1** [comment]
Na komplett geschlossen oiso wo nua grünland  und „boden&saat“ do steht

**Comment by ValentinHoerzi** [comment]
![image](https://user-images.githubusercontent.com/38781974/109979301-0823ca00-7cff-11eb-9f01-0e66943846db.png)
