### ISSUE TITLE
Order technologies by alphabet?

### ISSUE THREAD

**Issue by ValentinHoerzi** [ValentinHoerzi/Diplomarbeit-ERM#21]
Schaut findi dawei nu zu random aus, oda?

**Comment by Schoergi1** [comment]
jo des wa nu a plan gwen de woche das i des a bissl ordne, aber i würds iwie ned nach alphabet sondern a weng wos zusammenhängt

**Comment by Schoergi1** [comment]
Hab de Order so gändert das für mich irgendwie an sinn macht
Schau das oba bitte moi an de Überschriften an ob ds für die a passen würde daun kina ma den issue closen

**Comment by ValentinHoerzi** [comment]
Schaut findi voi guad aus, es san de programmiersprachen und technologien dazua hoid, de IDE's, versionsverwaltung und dann de additional API's
