### ISSUE TITLE
Gendern

### ISSUE THREAD

**Issue by Schoergi1** [ValentinHoerzi/Diplomarbeit-ERM#22]
I höt den text sxhau ausagsuacht, den ma oben hinschreibt dass alle angsprochenwerden mid da männlichen form

**Comment by ValentinHoerzi** [comment]
Was?

**Comment by Schoergi1** [comment]
den schreibt ma irgendwie am anfang das mit der männlichen Form alle angesprochen werden.  oba do frogn ma am freitag in Sickinger numoi

**Comment by ValentinHoerzi** [comment]
save

**Comment by ValentinHoerzi** [comment]
Hast du ds scho gmocht?

**Comment by Schoergi1** [comment]
Na do homa gsogt do frogn ma am freitag nu

**Comment by Schoergi1** [comment]
steht jz in da einleitung
