### ISSUE TITLE
Use my Location

### ISSUE THREAD

**Issue by ValentinHoerzi** [ValentinHoerzi/Diplomarbeit-ERM#23]
Soweit i mi erinnern kann hast du des programmiert oda? Kunntast du des dann beschreiben, weil i hab ned wirklich an Plan wos des mocht

**Comment by Schoergi1** [comment]
jop 
Ba de technologien oda in wos fia a kapitel?

**Comment by ValentinHoerzi** [comment]
Na, i mach jz komfortfunktionen und i lass einfach den punkt use my location aus und du schreibst da dann afoch eini, in das_registrierungsformular.tex

**Comment by Schoergi1** [comment]
ok bast

**Comment by Schoergi1** [comment]
Is gemacht
