### ISSUE TITLE
To change

### ISSUE THREAD

**Issue by Schoergi1** [ValentinHoerzi/Diplomarbeit-ERM#25]
7.1 --> Es handelt sich hier um Methode, bei der: bei Methode hots irgendwas
      --> Dass sind verwandte Konzepte, die zuweilen synonym verwendet werden: Das statt Dass
      --> Sehen Sie CI/CD einfach : Sollen wir scho de Personen direkt ansprechen?
7.5 --> Packete is falsch: Pakete

Kurz vor 7.7.3 --> um dieses Anschließen in der Test-Stage zu testen. :::: Anschließend

Auf seite 42 steht "...[9].kaniko..."  soll das so zusammengeschrieben sein?

**Comment by ValentinHoerzi** [comment]
Danke dir, is ausgebessert!
