### ISSUE TITLE
Shopify

### ISSUE THREAD

**Issue by Schoergi1** [ValentinHoerzi/Diplomarbeit-ERM#26]
Woast du nu den Link wo shopify beschrieben is weil i find den ned

**Comment by ValentinHoerzi** [comment]
https://shopify.dev/docs/admin-api/rest/reference den?

**Comment by Schoergi1** [comment]
Jo genau
weil i glaub der is nu ned beschrieben oderr?
Magst des schnell schauen weil daun dua i des nu

**Comment by ValentinHoerzi** [comment]
is ned na
