### ISSUE TITLE
Bilder zuschneiden?

### ISSUE THREAD

**Issue by Schoergi1** [ValentinHoerzi/Diplomarbeit-ERM#27]
Viele Bilder san jo von der kompletten Seite, das ma a sieht wie des im ganzen aussieht. Aber soll ma ein paar Bilder zuschneiden, das nua des angesprochene zu sehen is und des ganze drumherum ned?

**Comment by ValentinHoerzi** [comment]
i glb i hab mi um des wos du grod manst scho kümmert, zumindest bei de technologien

**Comment by Schoergi1** [comment]
Ja i würd a gern  irgendwie de anwendersicht so mocha oba eha gemeinsam

oiso i schreib de bilder do eina beim durchlesen de i vaändern würd und du schaust da de dann numoi an und sogst daun du a oda eben ned won ds basd

**Comment by ValentinHoerzi** [comment]
passt für mi
