### ISSUE TITLE
Sickinger Fragen:

### ISSUE THREAD

**Issue by ValentinHoerzi** [ValentinHoerzi/Diplomarbeit-ERM#5]
Kapitel 1: Einleitung oder Projektteam?

**Comment by Schoergi1** [comment]
1. Einleitung
1.1 Projektteam
1.2 Projektbetreuer
1.3 Auftraggeber(Pöttinger)
1.3.1 Ansprechpartner (Hubert, Dominik, Florian)

**Comment by Schoergi1** [comment]
Diplomarbeitswettbewerb?

**Comment by Schoergi1** [comment]
generelles feedback (Textstruktur, Verwendung und formattierung von Bilder)

**Comment by ValentinHoerzi** [comment]
wo code hintergrund, wo nur italic
