### ISSUE TITLE
3.15.1. GitHub -> Screenshot von Github.com anstatt GitHub Desktop?

### ISSUE THREAD

**Issue by ValentinHoerzi** [ValentinHoerzi/Diplomarbeit-ERM#7]

**Comment by ValentinHoerzi** [comment]
Und Screenshot der GitLab Pöttinger startseite bei 3.15.2 ?

**Comment by Schoergi1** [comment]
Github is changed

**Comment by Schoergi1** [comment]
> Und Screenshot der GitLab Pöttinger startseite bei 3.15.2 ?

ich weiß nicht ob wir von der git.poettinger Seite wo man die Ordner sieht einen Screenshot einfügen dürfen

**Comment by ValentinHoerzi** [comment]
> > Und Screenshot der GitLab Pöttinger startseite bei 3.15.2 ?
> 
> ich weiß nicht ob wir von der git.poettinger Seite wo man die Ordner sieht einen Screenshot einfügen dürfen

I Frage amoi in Florian
