### ISSUE TITLE
7. Anwendersicht

### ISSUE THREAD

**Issue by ValentinHoerzi** [ValentinHoerzi/Diplomarbeit-ERM#8]
I würds sauberer finden, wenn wiaklich nur der Screenshot von der Website do is und ned des ganze Opera rundherum, also de linke sidebar und oben de tabs

**Comment by ValentinHoerzi** [comment]
würde ah bei 7.2 einfach einen längeren Screenshot, anstatt 2 machen

**Comment by ValentinHoerzi** [comment]
Wie sieht es mit der Formulierung der Sätze aus?

**Comment by Schoergi1** [comment]
> Wie sieht es mit der Formulierung der Sätze aus?

was meinst damit?

**Comment by ValentinHoerzi** [comment]
> > Wie sieht es mit der Formulierung der Sätze aus?
> 
> was meinst damit?

z.b 7.1: .. muss man davor in der Länderwahl..
z.b 7.3.2: ..der Benutzer muss angeben, ob er auf dem eigenen landwirtschaftlichen Betrieb arbeitet..

Also so im sinne von: kann man des so schreiben, also so um des zu machen muss der benutzer das machen oder eher so, Um anzugeben, ob der Benutzer auf einem landwirtschaftlichen Betreib arbeitet, besteht die Möglichkeit des und des zu mochn

**Comment by Schoergi1** [comment]
Bilder sind überarbeitet

Die 2 angesprochenen Punkte sind einmal geändert

Weitere Formulierungen müssen zum Schluss noch in der ganzen Datei darübergelesen werden
